# Generated by Django 5.0.4 on 2024-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='razon_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
