# Generated by Django 5.0.4 on 2024-06-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_init_permisos'),
    ]
    def insertData(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        User = apps.get_model('auth', 'User')
        Cliente = apps.get_model('pedidos', 'Cliente')
        client_group = Group.objects.get(name='client')

        clients_without_role = Cliente.objects.filter(user__groups=None)
        for client in clients_without_role:
            client.user.groups.add(client_group)




    operations = [
        migrations.RunPython(insertData),
    ]
