from .simple_serializers import SimpleClienteSerializer, SimpleUserSerializer, SimpleProductoSerializer
from .pedido_viewset import PedidoViewSet, PedidoSerializer
from .cliente_viewset import ClienteViewSet, ClienteSerializer
from .producto_viewset import ProductoViewSet, ProductoSerializer
from .organization_viewset import OrganizationViewSet