# Generated by Django 4.2.11 on 2024-03-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='universidad.persona')),
                ('materias_inscritas', models.ManyToManyField(to='universidad.materia')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='universidad.semestre')),
            ],
        ),
    ]
