# Generated by Django 5.0.6 on 2024-05-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='viajes.avion')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='viajes.ruta')),
            ],
        ),
    ]
